<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable = no, shrink-to-fit=no">
        <title>404 PAGE NOT FOUND.</title>
        <style type="text/css">
            
            p { width:100%; margin-left:auto; font-size:30px; margin-right:auto; display:block; text-align:center; margin-top: 23%;}
        </style>
    </head>
    <body>
        <p>
            <b>404 PAGE NOT FOUND.</b>
        </p>
    </body>
</html>