<div class="container" style="margin-top:10px;">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Users</div>
            <!-- Table -->
            <table class="table">
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Last update</td>
                    <td></td>
                    <td></td>
                </tr>
                <?php foreach ($this->data as $k=>$v) { ?>
                    <tr>
                        <td><?=$k+1;?></td>
                        <td><?=$v['name'];?></td>
                        <td><?=$v['last_update'];?></td>
                        <td>
                            <a class="btn glyphicon glyphicon-edit" href="<?php echo $this->url('home').$this->lang; ?>/user/<?=$v['id'];?>/?act=detail" title="edit"></a>
                        </td>
                        <td>
                            <a class="btn glyphicon glyphicon-remove" href="<?php echo $this->url('home').$this->lang; ?>/user/<?=$v['id'];?>/?act=del" title="delete"></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
    <?php if($this->detail){ ?>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Edit User</div>
                <form class="navbar-form navbar-left" action="?act=edit" method="post">
                    <div class="form-group">
                        <input type="hidden" name="id" value="<?=$this->detail['id']; ?>">
                        <input type="text" class="form-control" placeholder="Name" name="name" value="<?=$this->detail['name']; ?>" required autofocus>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    <?php } ?>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Add New User</div>
            <form class="navbar-form navbar-left" action="?act=add" method="post">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Name" name="name" required autofocus>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <button type="submit" class="btn btn-default">Add</button>
            </form>
        </div>
    </div>
</div>